version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: nest_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: clementine_db
      MARIADB_USER: nestuser
      MARIADB_PASSWORD: nestpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: